pangeacyber/pangea-javascript

packages/pangea-node-sdk/src/types.ts, packages/pangea-node-sdk/tests/integration/redact.test.ts
=> Add count to redact responses

packages/react-auth/package.json, packages/react-auth/src/AuthProvider/index.tsx, packages/react-auth/src/ComponentAuthProvider/index.tsx, packages/react-auth/src/index.ts, packages/react-auth/src/shared/session.ts, packages/react-auth/src/types.ts
=> Add handling for refresh token a cookie.

packages/pangea-node-sdk/.gitlab-ci.yml
Reverts pangeacyber/pangea-javascript#160
=> Revert "Lint fix"

packages/react-auth/README.md, packages/react-auth/package.json, packages/react-auth/src/AuthNFlow/README.md, packages/react-auth/src/AuthProvider/README.md, packages/react-auth/src/AuthProvider/index.tsx, packages/react-auth/src/ComponentAuthProvider/README.md, packages/react-auth/src/ComponentAuthProvider/index.tsx, packages/react-auth/src/shared/hooks.ts, packages/react-auth/src/shared/session.ts, packages/react-auth/src/shared/types.ts, packages/react-auth/src/shared/utils.ts, packages/react-auth/src/types.ts
=> Fix state issues

packages/pangea-node-sdk/.gitlab-ci.yml, packages/pangea-node-sdk/tsconfig.json
=> Add alias for @src and @services

packages/pangea-node-sdk/src/services/authn/client/index.ts, packages/pangea-node-sdk/src/services/authn/client/password.ts, packages/pangea-node-sdk/src/services/authn/client/token.ts, packages/pangea-node-sdk/src/services/authn/session.ts
Begins writing out doc strings for the AuthN Node SDK
=> Doc strings for authn

packages/react-mui-authn/package.json, packages/react-mui-authn/src/components/Icons/facebook.tsx, packages/react-mui-authn/src/components/Icons/github.tsx, packages/react-mui-authn/src/components/Icons/google.tsx, packages/react-mui-authn/src/components/Icons/microsoft.tsx, packages/react-mui-authn/src/index.ts, packages/react-mui-authn/src/views/AuthFlow/components/EnrollMfaComplete/index.tsx, packages/react-mui-authn/src/views/AuthFlow/components/EnrollMfaStart/index.tsx, packages/react-mui-authn/src/views/AuthFlow/components/ResetPassword/index.tsx, packages/react-mui-authn/src/views/AuthFlow/components/SelectMfa/index.tsx, packages/react-mui-authn/src/views/AuthFlow/components/Signup/index.tsx, packages/react-mui-authn/src/views/AuthFlow/components/Start/index.tsx, packages/react-mui-authn/src/views/AuthFlow/components/VerifyCaptcha/index.tsx, packages/react-mui-authn/src/views/AuthFlow/components/VerifyEmail/index.tsx, packages/react-mui-authn/src/views/AuthFlow/components/VerifyMfaComplete/index.tsx, packages/react-mui-authn/src/views/AuthFlow/components/VerifyPassword/index.tsx, packages/react-mui-authn/src/views/AuthFlow/components/VerifySocial/index.tsx, packages/react-mui-authn/src/views/AuthFlow/index.tsx, packages/react-mui-authn/src/views/AuthFlow/types.ts, packages/react-mui-authn/yarn.lock
Add social icons, support react 17 & 18.
=> Remove direct use of auth provider in components.

packages/react-mui-branding/package.json, packages/react-mui-branding/src/components/BrandingThemeProvider/index.tsx, packages/react-mui-branding/src/utils.ts
Fix input size for dense mode.
=> Add react 17 or 18 as peer deps

packages/react-auth/package.json, packages/react-auth/src/AuthProvider/index.tsx, packages/react-auth/src/ComponentAuthProvider/index.tsx
=> Remove handling for signup param.

packages/vanilla-js/package.json, packages/vanilla-js/src/AuthNFlowClient/index.ts, packages/vanilla-js/src/AuthNFlowClient/types.ts
=> Add types for password reset.

packages/react-mui-authn/package.json, packages/react-mui-authn/src/features/AuthFlow/views/Captcha/index.tsx, packages/react-mui-authn/src/features/AuthFlow/views/Profile/index.tsx
Don't submit empty captcha code.
=> Handle dynamic string and number fields.

packages/react-mui-authn/package.json, packages/react-mui-authn/src/components/fields/StringField/index.tsx, packages/react-mui-authn/src/features/AuthFlow/components/AuthOnetimeEmail/index.tsx, packages/react-mui-authn/src/features/AuthFlow/components/AuthOnetimePhone/index.tsx, packages/react-mui-authn/src/features/AuthFlow/components/AuthOptions/components.tsx, packages/react-mui-authn/src/features/AuthFlow/components/AuthOptions/index.tsx, packages/react-mui-authn/src/features/AuthFlow/components/AuthPassword/index.tsx, packages/react-mui-authn/src/features/AuthFlow/components/SocialOptions/index.tsx, packages/react-mui-authn/src/features/AuthFlow/components/index.tsx, packages/react-mui-authn/src/features/AuthFlow/views/Login/index.tsx, packages/react-mui-authn/src/features/AuthFlow/views/Start/index.tsx, packages/react-mui-authn/yarn.lock
Support for set_email required_for params.
=> Support for one-time phone/email prompt.

examples/authn/README.md
Update to say AuthN and add a capital P to Pangea.
=> Update README to AuthN

.gitlab-ci.yml, examples/.examples-ci.yml, examples/react-audit-log-viewer/.gitlab-ci.yml, packages/pangea-node-sdk/.gitlab-ci.yml, packages/pangea-node-sdk/CHANGELOG.md, packages/pangea-node-sdk/src/types.ts, packages/pangea-node-sdk/src/utils/utils.ts, packages/pangea-node-sdk/tests/integration/audit.test.ts, packages/pangea-node-sdk/tests/integration/authn.test.ts, packages/pangea-node-sdk/tests/integration/embargo.test.ts, packages/pangea-node-sdk/tests/integration/file_scan.test.ts, packages/pangea-node-sdk/tests/integration/intel.domain.test.ts, packages/pangea-node-sdk/tests/integration/intel.file.test.ts, packages/pangea-node-sdk/tests/integration/intel.ip.test.ts, packages/pangea-node-sdk/tests/integration/intel.url.test.ts, packages/pangea-node-sdk/tests/integration/intel.user.test.ts, packages/pangea-node-sdk/tests/integration/redact.test.ts, packages/pangea-node-sdk/tests/integration/utils.ts, packages/pangea-node-sdk/tests/integration/vault.test.ts, packages/react-auth/.gitlab-ci.yml, packages/react-mui-audit-log-viewer/.gitlab-ci.yml, packages/react-mui-authn/.gitlab-ci.yml, packages/react-mui-branding/.gitlab-ci.yml, packages/react-mui-shared/.gitlab-ci.yml, packages/react-mui-store-file-viewer/.gitlab-ci.yml, packages/vanilla-js/.gitlab-ci.yml
- Update examples.ci just to simplify it
=> Update `gitlab-ci.yml` to test against AWS and GCP

.husky/pre-commit, package.json
Refer: <https://github.com/typicode/husky/releases/tag/v9.0.1>
=> Simplify husky setup after v9 update (GEA-12321)

packages/pangea-node-sdk/tests/integration/audit.test.ts
=> audit change start date

.github/workflows/ci.yml
=> Remove prefetch step (GEA-12443)

packages/pangea-node-sdk/CHANGELOG.md, packages/pangea-node-sdk/src/request.ts
=> Fix put to presigned url

packages/react-mui-authn/package.json, packages/react-mui-authn/src/components/core/PasswordRequirements/index.tsx, packages/react-mui-authn/src/components/fields/PasswordField/index.tsx, packages/react-mui-authn/src/features/AuthFlow/components/AuthPassword/index.tsx
Update special chars help text alignment.
=> Don't show remember username on signup.

examples/authz/authz_cycle.mjs, packages/pangea-node-sdk/src/services/authz.ts, packages/pangea-node-sdk/src/types.ts, packages/pangea-node-sdk/tests/integration/authz.test.ts
Renamed "namespace" to "type" and changed endpoint paths to `/v1/`.
=> pangea-node-sdk: updates for AuthZ v1 (GEA-13602)

packages/react-mui-authn/package.json, packages/react-mui-authn/rollup.config.mjs, packages/react-mui-authn/src/components/fields/CheckboxField/index.tsx, packages/react-mui-authn/src/components/fields/CodeField/CodeInput.tsx, packages/react-mui-authn/src/components/fields/DateField/index.tsx, packages/react-mui-authn/src/features/AuthFlow/components/OtpForm/index.tsx, packages/react-mui-authn/src/features/AuthFlow/views/Profile/index.tsx, packages/react-mui-authn/yarn.lock
Handle network errors on OTP form.
Update attributes on OTP form.
=> Support checkbox and date profile fields.

packages/pangea-node-sdk/src/services/audit.ts
It's just "audit" in all the other examples.
=> pangea-node-sdk: remove mention of "auditGeneral" (PAN-15198)

packages/react-mui-store-file-viewer/CHANGELOG.md, packages/react-mui-store-file-viewer/package.json, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/CreateSharesButton/CreateShareModal.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/CreateSharesButton/ShareAuthenticatorField.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/CreateSharesButton/index.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/GetEmailLinkField.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/GetPasswordLinkField.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/GetPhoneLinkField.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/index.tsx, packages/react-mui-store-file-viewer/src/hooks/context.tsx
Refactor share context provider and moved it up a level.
Clear shareLink on share type change.
=> Fix share by email password validation.

packages/react-auth/package.json, packages/react-auth/src/AuthProvider/index.tsx, packages/react-auth/src/shared/hooks.ts, packages/react-auth/src/shared/session.ts, packages/react-auth/src/types.ts
=> Change refresh to return a promise, default refresh to undefined.

packages/react-mui-store-file-viewer/CHANGELOG.md, packages/react-mui-store-file-viewer/package.json, packages/react-mui-store-file-viewer/src/components/FileDropBox/index.tsx, packages/react-mui-store-file-viewer/src/components/ShareObject/utils.ts, packages/react-mui-store-file-viewer/src/components/StoreDataGrid/FolderPath.tsx, packages/react-mui-store-file-viewer/src/components/StoreDataGrid/index.tsx, packages/react-mui-store-file-viewer/src/components/StoreDownloadDataGrid/index.tsx, packages/react-mui-store-file-viewer/src/components/StoreFileViewer/index.tsx
Add state for display of drop zone in root.
=> Support for a single folder as virtualRoot.

packages/oauth-js/package.json, packages/react-auth/.gitlab-ci.yml, packages/react-auth/package.json, packages/react-mui-audit-log-viewer/.gitlab-ci.yml, packages/react-mui-audit-log-viewer/package.json, packages/react-mui-authn/package.json, packages/react-mui-branding/package.json, packages/react-mui-share-file-viewer/package.json, packages/react-mui-shared/package.json, packages/react-oauth/package.json, packages/vanilla-js/package.json, packages/webcomponents/package.json
Otherwise the default for scoped packages is to publish as private.
=> chore: explicit public access for all scoped pkgs (PAN-17394)
