packages/react-auth/src/AuthProvider/index.tsx
This doesn't include code for removing the `state` and `code` URL search parameters during the login flow.
I ran into more issues removing it from the AuthProvider side instead of the application side. Biggest issue being an extra page refresh from calling `window.location.replace` within `processLogin`
=> GEA-3432: set error during login flow when token check status is not successful

examples/intel/ip.mjs, packages/pangea-node-sdk/CHANGELOG.md, packages/pangea-node-sdk/src/services/intel.ts, packages/pangea-node-sdk/tests/integration/intel.test.ts
- Mark /lookup as deprecated
- Implement /reputation
(Pending this changes to be merged on live backend)
=> Rename /lookup endpoint to /reputation

packages/pangea-node-sdk/.gitlab-ci.yml, packages/pangea-node-sdk/yarn.lock
In e54e6876fef2d2ccff8f660f216cec3d2d72befa we updated crypto-js but did not update the lockfile.
=> pangea-node-sdk: update crypto-js in lockfile (GEA-11240) 

.gitlab-ci.yml, packages/pangea-node-sdk/.gitlab-ci.yml, packages/react-auth/.gitlab-ci.yml, packages/react-mui-audit-log-viewer/.gitlab-ci.yml, packages/react-mui-authn/.gitlab-ci.yml, packages/react-mui-branding/.gitlab-ci.yml, packages/react-mui-shared/.gitlab-ci.yml, packages/react-mui-store-file-viewer/.gitlab-ci.yml, packages/vanilla-js/.gitlab-ci.yml, scripts/publish.sh, scripts/tag_release.py, scripts/validate_latest_installed.sh
The apt package is named "python3-github", not "pygithub". <https://packages.debian.org/bookworm/python3-github>
Removed the installation of pip since we were not actually using it. In reality we _should_ be installing Python packages with pip, not apt, but I don't want to change too much here yet.
Also pinned the Node.js image version to make things more deterministic.
=> Fix SDK publishing (GEA-11855)

examples/file_scan/file_scan_request_upload_url_put.mjs
Fixed bug in pre signed `put-url` file scan example
The example was using `response.accepted_result?.accepted_status.upload_url` to parse the pre-signed URL while it should have been `response.accepted_result?.put_url`
=> fixed bug in parsing presigned url response in example

packages/react-mui-branding/.gitlab-ci.yml, packages/react-mui-branding/package.json, packages/react-mui-branding/rollup.config.js, packages/react-mui-branding/yarn.lock
rollup-plugin-terser has been deprecated for years.
=> react-mui-branding: replace rollup-plugin-terser (GEA-12274)

packages/pangea-node-sdk/src/services/audit.ts
The param is named `event`, not `content`. Also remove types from this TSDoc as that is already derived from the TS.
=> pangea-node-sdk: correct `Audit.log()` param name (GEA-12282)

packages/pangea-node-sdk/.gitlab-ci.yml
The paths under `cache` need to be relative to the project's root directory. The paths defined in pangea-node-sdk's pipeline were written to be relative to pangea-node-sdk itself, but because they are read as relative to the project root nothing has been getting cached this whole time. This is clear from job logs:
Saving cache for successful job 00:01
Creating cache 0_yarn-e917e11da4cd6e873d1d40d7687bc1faf7f4e730-1-non_protected...
WARNING: node_modules: no matching files. Ensure that the artifact path is relative to the working directory (/builds/pangeacyber/pangea-javascript)
This patch fixes this issue by updating the paths to be relative to the project's root directory.
Refer: <https://docs.gitlab.com/ee/ci/yaml/#cache>
=> pangea-node-sdk: fix CI not caching dependencies (GEA-12312)

examples/.examples-ci.yml
4375574 removed the examples pipeline's `needs` on `pack_pangea_node_sdk`, despite the pipeline actually depending on the artifact output of that job. This causes the pipeline to fail on `main`:
$ pushd packages/pangea-node-sdk
/builds/pangeacyber/pangea-javascript/packages/pangea-node-sdk /builds/pangeacyber/pangea-javascript
$ tar -xf pangea-node-sdk-v*.tgz --strip-components 1 -C .
tar: pangea-node-sdk-v*.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
This patch adds back the `needs` to ensure that the required artifact is available.
=> Add `needs` back to examples pipeline (GEA-12320)

examples/.examples-ci.yml, packages/pangea-node-sdk/.gitlab-ci.yml
- Remove staging test job due to it won't be used
- Split jobs to allow_failure true and false
- Add integration tests job to examples needs. Do not want to waste resources testing examples if IT may not pass
=> Simplify CI

packages/pangea-node-sdk/CHANGELOG.md, packages/pangea-node-sdk/package.json, packages/pangea-node-sdk/src/utils/utils.ts, packages/pangea-node-sdk/tests/unit/utils.test.ts, packages/pangea-node-sdk/yarn.lock
Replace node-rs/crc32 with a pure-JS implementation of CRC32C so that pangea-node-sdk can more easily be added to Next.js projects without requiring the addition of a native addon loader like node-loader.
Verified working locally on @snpranav's Next.js App Router test app.
=> pangea-node-sdk: replace node-rs/crc32 (GEA-11594)

packages/react-mui-branding/package.json, packages/react-mui-branding/src/components/BrandingThemeProvider/index.tsx
Before, adding any changes to the components field in themeOptions directly would override the entire components object erasing all branding styles. This made it impossible to add a shadow root target for popovers and modals.
=> Add ability to override theme options before creating theme

packages/pangea-node-sdk/package.json, packages/pangea-node-sdk/tsconfig.json, packages/pangea-node-sdk/yarn.lock
The current Jest setup doesn't work with anything newer.
Discovered in https://github.com/pangeacyber/pangea-javascript/pull/831.
=> pangea-node-sdk: pin typescript to v5.1.6 (GEA-12960)

.gitlab-ci.yml, CONTRIBUTING.md, dev/validate_tag.sh, examples/.examples-ci.yml, packages/pangea-node-sdk/.gitlab-ci.yml
Publishing to the npm registry is now triggered via the pushing of Git tags instead of requiring the use of the one `release` branch. This enables flexibility in publishing prerelease versions outside of the `release` branch and shaves one step off of the manual release process (merging to `release`).
Instructions on how to publish a new version going forward have been added to `CONTRIBUTING.md`.
This only affects pangea-node-sdk because I did not want to disrupt how the other projects are being worked on at the moment. However, the changes here are versatile enough that it would be very easy for the other projects to "onboard".
=> pangea-node-sdk: refactor publish pipeline around Git tags (GEA-12973)

.github/workflows/ci.yml, packages/react-mui-authn/.gitignore
The project currently doesn't have a CI job that runs on PR branches. The current GitLab pipeline for it only runs on `main`.
=> chore: add CI job for react-mui-authn (GEA-13627)

.github/workflows/ci.yml, packages/react-auth/package.json, packages/react-auth/src/shared/utils.ts, packages/react-auth/yarn.lock
This fixes Remix Vite apps not recognizing that react-auth is a dual CJS+ESM package.
Verified working locally on a fresh Remix Vite app and our docs site.
=> react-auth: add "exports" field (GEA-13847)

packages/react-auth/.parcelrc, packages/react-auth/package.json, packages/react-auth/parcel-optimizer-use-client.mjs, packages/react-auth/src/AuthNFlow/mock.tsx, packages/react-auth/src/AuthNFlow/provider.tsx, packages/react-auth/src/AuthProvider/index.tsx, packages/react-auth/src/ComponentAuthProvider/index.tsx, packages/react-auth/yarn.lock
Use the `"use client";` directive on any component that depends on state and lifecycle events.
Added a custom Parcel optimizer plugin to ensure that the `"use client";` directive appears at the top of the bundled files, which is a requirement of that directive.
Verified working locally on a Next.js v14.2.2 app with App Router enabled.
=> react-auth: mark client entry points (GEA-13856)

packages/pangea-node-sdk/.gitlab-ci.yml
Limiting the base CI to just branch pushes is not really necessary, and we want it to run on tag pushes as well. So, remove the `if` rule.
=> pangea-node-sdk: run base CI on any type of push (GEA-14406)

packages/pangea-node-sdk/jest.config.mjs, packages/pangea-node-sdk/package.json, packages/pangea-node-sdk/yarn.lock
Replace ts-jest, which was holding us back from updating TS, with swc/jest. Then update TS to v5.4.5.
The config file had to be changed to a plain JS one because otherwise the same error remains. IMO this is an OK compromise, since it's just a config file, if it means newer TS for the rest of the project.
=>  pangea-node-sdk: update typescript to v5.4.5 (GEA-14160) 

packages/pangea-node-sdk/src/types.ts
No effect on public API, `Profile.first_name` is still accessible, these fields just won't be an explicit part of all profiles going forward.
=> pangea-node-sdk: remove `first_name` and `last_name` (PAN-15304)

packages/pangea-node-sdk/CHANGELOG.md, packages/pangea-node-sdk/src/types.ts
Also added other missing properties. Many of these do not have descriptions in the API documentation so the docs here are skim.
`enable` has been renamed to `enabled` to match the API's response schema. This is a breaking change but the current property isn't being deserialized properly anyways so it's been unusable this whole time.
=> pangea-node-sdk: add `"state"` to `Authenticator` (PAN-15469)

packages/pangea-node-sdk/CHANGELOG.md, packages/pangea-node-sdk/src/services/audit.ts, packages/pangea-node-sdk/src/services/authn/agreements/index.ts, packages/pangea-node-sdk/src/services/authn/client/index.ts, packages/pangea-node-sdk/src/services/authn/client/password.ts, packages/pangea-node-sdk/src/services/authn/client/session.ts, packages/pangea-node-sdk/src/services/authn/client/token.ts, packages/pangea-node-sdk/src/services/authn/flow/index.ts, packages/pangea-node-sdk/src/services/authn/index.ts, packages/pangea-node-sdk/src/services/authn/session.ts, packages/pangea-node-sdk/src/services/authn/user/authenticators.ts, packages/pangea-node-sdk/src/services/authn/user/index.ts, packages/pangea-node-sdk/src/services/authn/user/invites.ts, packages/pangea-node-sdk/src/services/authn/user/profile.ts, packages/pangea-node-sdk/src/services/authz.ts, packages/pangea-node-sdk/src/services/base.ts, packages/pangea-node-sdk/src/services/embargo.ts, packages/pangea-node-sdk/src/services/file_scan.ts, packages/pangea-node-sdk/src/services/intel.ts, packages/pangea-node-sdk/src/services/redact.ts, packages/pangea-node-sdk/src/services/vault.ts, packages/pangea-node-sdk/src/types.ts, packages/pangea-node-sdk/src/utils/multipart.ts
Accept Pangea token type in service constructors. Type must be 'pangea_token' or a raw string.
=> Create new Pangea token type

packages/pangea-node-sdk/tests/integration/audit.test.ts
Timeout was being set to 60s early on in the file, but then overwritten to 20s later on. This affects all tests here.
Both of these values are less than the default polling timeout of 120s, so this patch removes the duplicate `jest.setTimeout()` and sets the overall test timeout to the polling timeout plus some buffer. This way the polling timeout is hit before the test timeout.
=> pangea-node-sdk: raise timeout of Audit tests (PAN-16504)

packages/pangea-node-sdk/CHANGELOG.md, packages/pangea-node-sdk/package.json, packages/pangea-node-sdk/src/json-canon.d.ts, packages/pangea-node-sdk/src/utils/utils.ts, packages/pangea-node-sdk/tests/unit/utils.test.ts, packages/pangea-node-sdk/yarn.lock
Integration tests unveiled more canonicalization issues, this time surrounding the a-circumflex and replacement characters: <https://gitlab.com/pangeacyber/pangea-javascript/-/jobs/7734561427>
This patch fixes the issue by replacing all of the custom RFC8785 code with the json-canon library. Also added unit tests to cover what was previously failing.
=> pangea-node-sdk: correct canonicalization of more chars (PAN-16573)

packages/react-mui-authn/CHANGELOG.md, packages/react-mui-authn/package.json, packages/react-mui-authn/src/features/AuthFlow/components/AuthOnetimeEmail/index.tsx, packages/react-mui-authn/src/features/AuthFlow/components/AuthOnetimePhone/index.tsx, packages/react-mui-authn/src/features/AuthFlow/components/AuthPassword/index.tsx, packages/react-mui-authn/src/features/AuthFlow/views/Login/index.tsx, packages/react-mui-authn/src/stories/OneTime.stories.tsx, packages/react-mui-authn/src/stories/data/flow_onetime_email.json, packages/react-mui-authn/src/stories/data/flow_onetime_password.json, packages/react-mui-store-file-viewer/CHANGELOG.md, packages/react-mui-store-file-viewer/package.json, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/CreateSharesButton/CopyPasswordModal.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/CreateSharesButton/CreateShareModal.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/CreateSharesButton/index.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/GetEmailLinkField.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/GetPasswordLinkField.tsx, packages/react-mui-store-file-viewer/src/components/CreateNewShareButton/GetPhoneLinkField.tsx
- Show copy password after Share via Email password share create
- Correct text above password input for Get Link
Update text on one-time auth login screens.
=> Share UX updates

.github/workflows/ci.yml, packages/react-mui-share-file-viewer/CHANGELOG.md, packages/react-mui-share-file-viewer/package.json, packages/react-mui-share-file-viewer/rollup.config.mjs, packages/react-mui-share-file-viewer/yarn.lock
With the addition of `preserveModules`, the generated ESM entry became `dist/esm/src/index.js`, but in `package.json` we had the entry defined as `dist/esm/index.js`. This causes ESM imports to fail in places like @pangeacyber/webcomponents. This patch fixes the issue by disabling `preserveModules`. To help prevent this from happening again, publint is also added since it catches this exact issue.
=> react-mui-share-file-viewer: fix ESM import

scripts/publish.sh
yarn v4 uses `yarn npm publish`, while yarn v1 uses `yarn publish`. So, update the publish script to check the current yarn version and use the correct command.
=> scripts: use `yarn npm publish` for yarn v4

examples/redact/README.md, examples/redact/package.json, examples/redact/redact_structured.mjs, examples/redact/text_llm_request.mjs, examples/redact/unredact.mjs, examples/redact/yarn.lock, packages/pangea-node-sdk/CHANGELOG.md, packages/pangea-node-sdk/src/types.ts
The typing around `redaction_method_overrides` was slightly wrong; the field accepts a object where the keys are the rule name and the values are the overrides. I fixed that and also made the typing stricter so that things like e.g. `fpe_alphabet` can only be specified if `redaction_type: "fpe"`.
=> pangea-node-sdk: correct redaction method overrides, add examples

.github/workflows/ci.yml, .gitlab-ci.yml, examples/.examples-ci.yml, packages/pangea-node-sdk/CHANGELOG.md, packages/pangea-node-sdk/README.md, packages/pangea-node-sdk/package.json, packages/pangea-node-sdk/src/config.ts, packages/pangea-node-sdk/src/errors.ts, packages/pangea-node-sdk/src/file_uploader.ts, packages/pangea-node-sdk/src/request.ts, packages/pangea-node-sdk/src/services/base.ts, packages/pangea-node-sdk/src/services/file_scan.ts, packages/pangea-node-sdk/src/types.ts, packages/pangea-node-sdk/tests/integration/audit.test.ts, packages/pangea-node-sdk/tests/integration/file_scan.test.ts, packages/pangea-node-sdk/tests/integration/sanitize.test.ts, packages/pangea-node-sdk/tests/integration/share.test.ts, packages/pangea-node-sdk/tests/unit/config.test.ts, packages/pangea-node-sdk/yarn.lock
Add `baseUrlTemplate` to `PangeaConfig` to allow for greater control over the complete API URL. This option may be a full URL with the optional `{SERVICE_NAME}` placeholder, which will be replaced by the slug of the respective service name. This supersedes `environment` and `insecure`.
=> pangea-node-sdk: add `baseUrlTemplate`

packages/pangea-node-sdk/CHANGELOG.md, packages/pangea-node-sdk/package.json, packages/pangea-node-sdk/src/request.ts, packages/pangea-node-sdk/src/services/audit.ts, packages/pangea-node-sdk/src/services/base.ts, packages/pangea-node-sdk/src/services/management.ts, packages/pangea-node-sdk/src/services/redact.ts, packages/pangea-node-sdk/src/types.ts, packages/pangea-node-sdk/yarn.lock
Some of the new APIs don't follow the standard Pangea response schema, so a little bit of refactoring is required. Also, there is more usage of GET requests with query parameters, so there are changes here to support that as well.
=> pangea-node-sdk: add Management and Config APIs
